project:
  type: book
  output-dir: _book
  resources:
    - og-image.png
    - cover.png

book:
  title: "Communicating Uncertainty"
  author:
    - name: Bahman Rostami-Tabar
      url: https://bahmanrostamitabar.github.io/
  date: today
  date-format: long
  
  cover-image: cover.png
  favicon: cover.png

  site-url: https://bahmanrostamitabar.github.io/communicate_uncertainty/
  repo-url: https://github.com/bahmanrostamitabar/communicate_uncertainty
  repo-actions: [edit, issue]

  search: true
  sharing: [twitter, linkedin]
  open-graph:
    title: "Communicating Uncertainty"
    description: "A practical cross-disciplinary reference for communicating
      uncertainty."
    image: https://raw.githubusercontent.com/bahmanrostamitabar/communicate_uncertainty/main/og-image.png
    image-alt: "Book cover for Communicating Uncertainty by Bahman Rostami-Tabar"
    locale: en_GB
 
  twitter-card:
    title: "Communicating Uncertainty"
    description: "A practical cross-disciplinary reference for communicating
      uncertainty."
    image: https://raw.githubusercontent.com/bahmanrostamitabar/communicate_uncertainty/main/og-image.png
    image-alt: "Book cover for Communicating Uncertainty by Bahman Rostami-Tabar"
    card-style: summary_large_image
    creator: "@Bahman_R_T"

  navbar:
    background: primary
    search: true

  sidebar:
    style: docked
    search: true

  chapters:
    - index.qmd

    - part: "Part I: Foundations"
      chapters:
        - 01_introduction.qmd
        - 02_conceptualising_uncertainty.qmd
        - 03_sources_of_uncertainty.qmd
        - 04_related_concepts.qmd

    - part: "Part II: Why and To Whom"
      chapters:
        - 05_why_communicate.qmd
        - 05_1_users.qmd

    - part: "Part III: Methods"
      chapters:
        - 06_0_method_intro.qmd
        - 06_1_forecast_trajectories.qmd
        - 06_2_fan_charts.qmd
        - 06_3_distributions.qmd
        - 06_4_prediction_intervals.qmd
        - 06_5_categorical.qmd
        - 06_6_scenarios.qmd
        - 06_7_verbal.qmd
        - 06_8_numerical.qmd

    - 07_conclusion.qmd
    - references.qmd

bibliography: references.bib
csl: https://www.zotero.org/styles/apa

format:
  html:
    theme:
      light: journal
      dark: slate
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    number-sections: true
    number-depth: 3
    smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    link-external-icon: true
    link-external-newwindow: true
    fig-cap-location: bottom
    tbl-cap-location: top
    grid:
      sidebar-width: 280px
      body-width: 900px
      margin-width: 200px

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
